welcome_message:
  # Whether if the welcome public message module should be enabled.
  enable_public_message: true
  # Whether if the welcome private message module should be enabled.
  enable_private_message: true
  # The public welcome message. Leave "" to remove the join message.
  public_message: "&e%name% joined the server"
  # The private welcome message.
  private_message: "&7Welcome back %name%!"


first_join_welcome_message:
  # Whether if the first join welcome public message module should be enabled.
  enable_public_message: true
  # Whether if the first join welcome private message module should be enabled.
  enable_private_message: true
  # The public first join welcome message. Leave "" to remove the first join message.
  public_message: "&e%name% joined the server for the first time!"
  # The private first join welcome message.
  private_message: "&7Welcome to the server %name%!"


welcome_title:
  # Whether if the welcome title module should be enabled.
  enable_title: true
  # The title
  title: "WELCOME %name%"
  # The subtitle. Leave "" if you don't want any subtitle
  subtitle: ""
  # Time in seconds for the title to fade in.
  fadeIn: 0.5
  # Time in seconds for the title to stay.
  stay: 3.5
  # Time in seconds for the title to fade out.
  fadeOut: 1.0


welcome_sound:
  # Whether if the welcome sound module should be enabled
  enabled_sound: true
  # The sound that would be played.
  # List of available sounds:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html.
  sound: "ENTITY_PLAYER_LEVELUP"
  # The sound volume.
  # As the sound is private ranges between 0.1 and 1.0.
  volume: 1.0
  # The sound pitch.
  # Ranges between 0.5 and 2.0.
  # 1.0 normal speed, 0.5 half speed, 2.0 double speed.
  pitch: 1.0


welcome_actionbar:
  # Whether if the action bar module should be enabled
  enabled_actionbar: true
  # The message that will be displayed at the action bar
  message: "&eWelcome dear %name%!"
  # Time in seconds the action bar message will be shown
  duration: 4.5